apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30081